### ISSUE TITLE
[$30] Support error message pop-up during challenge loading

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/challenge-engine-ui#328] opened 2020-05-08 14:28 UTC
**Describe the bug**
An error message appears then disappears after loading into a specific completed challenge

**To Reproduce**
3. Click the "Completed" challenges tab
4. Click the first project "https://challenges.topcoder-dev.com/projects/null/challenges/c8e71bcf-d091-4319-9e99-b6a9082fc1e0/edit"
5. Observe the pop-up error message 

**Expected behavior**
There should be no error message when the challenge is loading in the page correctly. The error should only appear when the challenge fails to load

**Screenshots**
[errormessage.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/4599163/errormessage.zip)
![supporterror](https://user-images.githubusercontent.com/37167721/81409570-03769f80-9148-11ea-9d11-8487cb09fb97.png)

**Desktop:**
 - OS: (Official Build) Built on Ubuntu , running on Ubuntu 16.04 
 - Browser: Chrome
 - Version: 81.0.4044.122
**Additional context**
There is an error pop-up when loading a completed challenge and the error then disappears after complete loading

**Comment by jmgasper** [comment] 2020-05-12 00:31
Contest https://www.topcoder.com/challenges/30125144 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-05-12 00:32
Contest https://www.topcoder.com/challenges/30125144 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by suppermancool** [comment] 2020-05-12 05:49
@jmgasper i can't reproduce this bug, can you check again?

**Comment by jmgasper** [comment] 2020-05-17 01:17
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed by jmgasper** 2020-05-17 01:17 UTC
Labels: Accepted, Functional, May 7 Bug Hunt, question, tcx_Assigned

**Comment by jmgasper** [comment] 2020-06-01 19:43
This has been paid
