### ISSUE TITLE
[$40] Fix project page to pull the project by ID

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-engine-ui#148] opened 2020-04-23 22:22 UTC
**NOTE** - We need to do this everywhere we expect to pull project information.  If there are other places we do this, please let me know and I can bump the payment accordingly to offset the additional work.

### Currently
On the project page, we are using the ID given in the path to match with the project from `https://api.topcoder-dev.com/v5/projects`, and then we use the matched record to fill in the UI.

An example is:

https://challenges.topcoder-dev.com/projects/3801/challenges

### New change

Now, I'd like to ensure that the data loaded for the project shown on the page actually comes from a secondary request to:

`https://api.topcoder-dev.com/v5/projects/{project id}`

The reason for this is that we are finding certain projects that are accessible for the user *are not* coming back in the project list for that same user.

An example is project ID 9155 for user `jcori / appirio123`.  This comes back from https://api.topcoder-dev.com/v5/projects/9155, but is *not* in the projects list for that user.  This will allow us to deep-link into the challenge engine UI more accurately.

**Comment by jmgasper** [comment] 2020-04-23 22:24
Contest https://www.topcoder.com/challenges/30122964 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-04-23 23:04
Contest https://www.topcoder.com/challenges/30122964 has been updated - it has been assigned to azilkie.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by awzilkie** [comment] 2020-04-24 01:04
@jmgasper see PR here: https://github.com/topcoder-platform/challenge-engine-ui/pull/158
Not sure if this is the fix you're looking for. As far as I can tell the only place in the code where we use stored data from the projects API is getting the members list for a challenge. The rest of the data comes from the challenge API. Is there a reproducible issue to test here?

**Comment by jmgasper** [comment] 2020-04-24 01:09
@awzilkie - When logged in as `jcori` / `appirio123`, try loading these URLs:

https://challenges.topcoder-dev.com/projects/9155/challenges
https://challenges.topcoder-dev.com/projects/3108/challenges

![Screen Shot 2020-04-24 at 11 09 06](https://user-images.githubusercontent.com/21790/80164333-06d43c00-861c-11ea-9f5e-7bee977a9e82.png)

Note that the projects don't load properly.  I think this is because the actual project details aren't found in the current project list.  In the network requests, I don't see any request to https://api.topcoder-dev.com/v5/projects/3108, as an example.

**Comment by awzilkie** [comment] 2020-04-24 01:14
@jmgasper I don't think you would expect to see a request to the projects endpoint in this case. All the data comes from the challenges API

**Comment by awzilkie** [comment] 2020-04-24 01:14
but my fix will pull the members data now from the projects API when you load this url

**Comment by jmgasper** [comment] 2020-04-24 01:15
@awzilkie - I would expect the page to *work* though.  It doesn't now, even though https://challenges.topcoder-dev.com/projects/3108/challenges is a valid project ID.

**Comment by jmgasper** [comment] 2020-04-24 01:16
And, after further testing with the fix, it still doesn't work.

**Comment by jmgasper** [comment] 2020-04-24 01:16
![Screen Shot 2020-04-24 at 11 16 27](https://user-images.githubusercontent.com/21790/80164696-0b4d2480-861d-11ea-98a2-bacc126c80d1.png)

**Comment by jmgasper** [comment] 2020-04-24 01:18
@awzilkie - I would expect to see a request to https://api.topcoder-dev.com/v5/projects/9155 be made.  Right now, I think the code is trying to just match the given project ID with details loaded for the side menu, but the side menu doesn't contain the full list of projects, which is something we're dealing with in other tickets.  You can't assume that the given project ID will match a project in the list from `https://api.topcoder-dev.com/v5/projects`

**Comment by awzilkie** [comment] 2020-04-24 01:26
@jmgasper no the code does not make a request to the projects API right now when loading https://challenges.topcoder-dev.com/projects/3108/challenges. It pulls all of the data from the challenge API (except the members). If the issue is to fix the https://challenges.topcoder-dev.com/projects/3108/challenges page then it has nothing to do with the projects API

**Comment by awzilkie** [comment] 2020-04-24 01:27
If you want me to fix the loading of https://challenges.topcoder-dev.com/projects/3108/challenges I can go ahead and have a look but it might have a bigger scope that what was described in the issue

**Comment by jmgasper** [comment] 2020-04-24 01:28
Yes, it needs to be fixed.  I'll bump the payment.

**Comment by jmgasper** [comment] 2020-04-24 02:47
@awzilkie - Just checking in here - do you need anything from me?  This one's kind of a high priority, thanks.

**Comment by awzilkie** [comment] 2020-04-24 03:29
Sorry I don't think I can get to this until tomorrow (I am in EST timezone). If you need it done before then feel free to assign it to someone else.

**Comment by jmgasper** [comment] 2020-04-25 00:01
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30122964<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2020-04-25 00:00 UTC
Labels: tcx_FixAccepted
