### ISSUE TITLE
[$25] Challenge Schedule > Timeline phases disappears when user select out of range date

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#466] opened 2020-05-08 15:37 UTC
![image](https://user-images.githubusercontent.com/42398485/81421938-e629dd00-9117-11ea-98c0-60b0e3be1e8a.png)

**URL:**
https://challenges.topcoder-dev.com/projects/16529/challenges/a9344fca-a518-4692-9c69-8af9956fab0d/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user
2. Go to 'Draft' and Click on a Challenge (It will open the Edit Challenge)
3. Enter date= 05/23/2020 to Start Date
4. Look at the chart

**Actual Result:** 

- Challenge Schedule > Timeline phases disappear when user select out of range date

**Expected Result:** 

- Should display the phases even though the user selects an out of range date. Should display a validation or if it is allowed the chart should be scrollable to see the chart

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by codejamtc** [comment] 2020-05-08 15:38
Timeline dates are also not updating:
![image](https://user-images.githubusercontent.com/42398485/81422070-1a050280-9118-11ea-8fe0-25d633b27968.png)

**Comment by jmgasper** [comment] 2020-05-10 06:08
Contest https://www.topcoder.com/challenges/30124905 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-05-10 06:09
Contest https://www.topcoder.com/challenges/30124905 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by suppermancool** [comment] 2020-05-10 10:38
@jmgasper i can't reproduce this . i set  `05/23/2020` or `06/30/2020` as start but the gantt chart still work correctly

<img width="1020" alt="Screen Shot 2020-05-10 at 17 38 13" src="https://user-images.githubusercontent.com/5815182/81496879-0fe42f00-92e5-11ea-8817-f0f63be1bb8a.png">

**Comment by jmgasper** [comment] 2020-05-19 22:52
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed by jmgasper** 2020-05-19 22:52 UTC
Labels: Accepted, Functional, May 7 Bug Hunt, question, tcx_Assigned

**Comment by jmgasper** [comment] 2020-06-01 19:43
This has been paid
