### ISSUE TITLE
Copilot is not selected if a user saves a challenge as a Draft for a different Copilot 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#565] opened 2020-05-08 23:25 UTC
https://monosnap.com/file/TzCoivNNI7EYvWdxRGQ7RTL9ZNcfGE

**URL:**
https://challenges.topcoder-dev.com/projects/16539/challenges/138f7b3b-6be1-43ee-b4ff-40856a798f07/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Select a Project (eg: Test & QA) > Click Launch New > Fill All > Click Create Challenge
3. Fill all the details in the form
4. From the Copilot selection select a different copilot (Ghostar)(NOT the logged in user)
5. Click "Launch as Draft"
6. Check the Draft challenges tab (It won't display)

7. Open the application and Login as a valid user (Ghostar)
8. Select Project Selected in Step 2
9. Go to Draft Tab
10. Open the challenge
11. Check the Copilot value

**Actual Result:** 

- Copilot is not selected from the Copilot field (But if we have a challenge for the current user Copilot value is selected. This is also not because of the delay occurred for displaying data mentioned here https://github.com/topcoder-platform/challenge-engine-ui/issues/306
- Note here is saving the challenge for same or different user won't display the values added to "Internal Review Type, View Advance Settings and Limit

**Expected Result:** 

- Should display the Copilot value selected
- If we save the same challenge for the logged-in user the Copilot value is saved

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by codejamtc** [comment] 2020-05-08 23:53
https://monosnap.com/file/i1brzKxknImqngrrUMgoBcPqoojTRX

**Comment by acshields** [comment] 2020-06-02 21:18
@vikasrohit - Can you test this out to see if you get the same behavior? If so, what would be your estimate on level of effort to correct? I am going to put this in the pre-prod release fixes for now.

**Comment by vikasrohit** [comment] 2020-06-08 11:44
@drasticdpk can you please help me in reproducing this one? I tried it on local and dev env both, but it is not happening for me as of now. It would be great if you can try to reproduce it and refine the steps to reproduce, may be I am missing something here.

**Comment by drasticdpk** [comment] 2020-06-08 14:55
@vikasrohit  Here is my finding :
To meet the above scenario, we need project which has at least 2 member for copilot Role.
For this I have taken this [project](https://challenges.topcoder-dev.com/projects/16541/challenges) with **jcori** & **ghoster** copilot role.
For me, For track Development, it is working as expected.
![image](https://user-images.githubusercontent.com/25297859/84044504-649fc600-a9c7-11ea-8164-fae32e805d72.png)
But track Design we are having below issue 
1. When we select/chose any group 
![image](https://user-images.githubusercontent.com/25297859/84044844-cceea780-a9c7-11ea-80be-ca65dae86037.png)

2. without selecting any group,
![image](https://user-images.githubusercontent.com/25297859/84045012-045d5400-a9c8-11ea-928a-5983defd2260.png)

**Comment by vikasrohit** [comment] 2020-06-09 13:26
Thanks @drasticdpk 

I think the main observation here is that original issue is not reproducible any more. The issue with design track seems to be already logged #473. Even if it is not the same issue, I think design track issue is not letting us to follow the steps for the current issue and we are not able to reproduce the current issue with other tracks. So, I would like to close this one and file a new one if it is different from #473.

**Comment by drasticdpk** [comment] 2020-06-09 14:06
Ok noted @vikasrohit

**Closed by drasticdpk** 2020-06-09 14:06 UTC
Labels: Accepted, Functional, May 7 Bug Hunt, P1
