### ISSUE TITLE
Copilots are not being added the the direct project

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#814] opened 2020-09-16 14:42 UTC
[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5232833/2.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as codejam
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Create a draft 
4. Click OR or Direct

### Actual behavior
- Unable to Navigate challenge OR/Direct app

### Expected behavior
- Should be able to Navigate challenge OR/Direct app

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `codejam`

**Comment by drasticdpk** [comment] 2020-09-16 16:19
@vikasrohit ,
During the preliminary investigation, what I found here is, project should be sync between WM and direct app. 
If it is true, please help us to setup few projects with copilot credential (topcoderconnect+copilot@gmail.com), so we will use this acc for test case/scenario verification. cc @codejamtc @lakshmiathreya 
 Reference 
https://monosnap.com/file/WGzAdVbHbc6BAM6rgrGG3BviPyYzQx

**Comment by vikasrohit** [comment] 2020-09-17 06:38
@drasticdpk yes, project should be in sync between v5 and legacy and there are few areas where it has some pain points like I explained in https://github.com/topcoder-platform/challenge-engine-ui/issues/807#issuecomment-693276866.

I think this issue is duplicate of https://github.com/topcoder-platform/challenge-engine-ui/issues/807, it would be better to close this one to avoid duplicates. However, if this issue is created in response to https://github.com/topcoder-platform/challenge-engine-ui/issues/807#issuecomment-693295051, then I guess the issue title and its description should be different, it should say something like `Copilots are not added to direct project when they are not in copilot pool`

**Comment by vikasrohit** [comment] 2020-09-22 11:03
@codejamtc @drasticdpk fixed the issue with copilots not being synced to the legacy project, root cause was https://github.com/topcoder-platform/legacy-project-processor/issues/17

**Comment by codejamtc** [comment] 2020-09-23 02:56
@vikasrohit I am using my copilot account `copilot_codejam` to test the ticket and when I am trying to access the Direct link it shows me `Sorry, you don't have permission to access this contest.`

**Comment by vikasrohit** [comment] 2020-09-24 09:19
@codejamtc are you testing it on production or dev? You mentioned link of dev but project name is from production. I think this issue was not reproducible on dev earlier as well and could be reproduced only on prod. You have get yourself removed from the culprit project and get yourself added back to the project to get it fixed. Further, your account is not in copilot pool on prod, so you would still face the same issue on prod, it should be fixed for @drasticdpk because he is already in copilot pool on production.

**Comment by codejamtc** [comment] 2020-09-24 12:38
Noted, Thanks

**Comment by lakshmiathreya** [comment] 2020-09-24 13:48
@vikasrohit copilot_codejam is in Copilot pool in Dev. I added him yesterday using Tony's tool ...

**Comment by vikasrohit** [comment] 2020-09-25 10:48
Ok, but still he has to be removed from connect project and then added back to the project to see the effect of the fix.

**Comment by drasticdpk** [comment] 2020-09-28 07:29
@vikasrohit ,
Project is listing on direct app but I am unable to fetch challenge which I have created form WM. Please assist to solve this issue.
![image](https://user-images.githubusercontent.com/25297859/94402873-53541280-018c-11eb-8965-eeee2f02d7b8.png)

**Comment by vikasrohit** [comment] 2020-09-28 08:18
@drasticdpk this might be an issue with direct api in dev, however, I think you can work around that by loading the project in the direct first and than load its challenges, does that work?

**Comment by rootelement** [comment] 2020-10-19 16:24
This is fixed as of last Thursday.

**Closed by rootelement** 2020-10-19 16:24 UTC
Labels: Dev Environment, Functional, P0, QA Fail in Dev
