### ISSUE TITLE
[$15] Sometimes the tooltip stay opened; when user move the cursor away from the chart

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#515] opened 2020-05-08 17:01 UTC
![image](https://user-images.githubusercontent.com/42398485/81429644-b41e7800-9123-11ea-9034-328edd65fdbd.png)

https://monosnap.com/file/LBiYdfLFX5P4ojeEmFmdKIhxJ42EzQ

**URL:**
https://challenges.topcoder-dev.com/projects/16531/challenges/3f6452f7-db6a-4055-86fb-ffc681ac69be/edit

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Go to 'Draft' tab and click on a challenge
3. Go to 'Challenge Schedule :' > Edit
4. Hover over 'Review' text and move the cursor above appeal and then appeal response and then out of the chart
5. Observe

**Actual Result:** 

- Sometimes the tooltip stay opened; when user move the cursor away from the chart

**Expected Result:** 

- Should hide all the popups, if user is not focused on particular bar

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by jmgasper** [comment] 2020-05-10 02:50
Changing to a UI issue

**Comment by jmgasper** [comment] 2020-05-10 06:01
@narekcat - Assigned this to you, if you want it.

**Comment by jmgasper** [comment] 2020-05-10 06:04
Contest https://www.topcoder.com/challenges/30124898 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-05-10 06:05
Contest https://www.topcoder.com/challenges/30124898 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by narekcat** [comment] 2020-05-10 15:30
@jmgasper . I have examined the issue and found out that the problem is with Gantt Chart. I have tried and find the same issue in Gantt Chart [demo ](https://react-google-charts.com/gantt-chart).
![challenge-engine-ui-issue-with-gantt-chart-tooltip](https://user-images.githubusercontent.com/11549629/81503361-42495880-92f4-11ea-925e-c965f5fe856b.png)
Also there is similar [issue ](https://github.com/rakannimer/react-google-charts/issues/332) in Gantt Chart [repository](https://react-google-charts.com/gantt-chart).
What I need to do ?

**Comment by jmgasper** [comment] 2020-05-10 21:38
@narekcat - Ok, we'll just leave it as-is for now, thanks.

**Closed by jmgasper** 2020-05-10 21:38 UTC
Labels: Accepted, May 7 Bug Hunt, User Interface, question, tcx_Assigned, tcx_FixAccepted

**Comment by jmgasper** [comment] 2020-05-10 21:39
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30124898<br/><br/>```This is an automated message for ghostar via Topcoder X```
