### ISSUE TITLE
[$15] Order of the phases are incorrect in Challenge creation process

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#555] opened 2020-05-08 20:03 UTC
https://monosnap.com/file/4LlHQbpxJhD5LbF7vm1l6NtlYdzCic

**URL:**
https://challenges.topcoder-dev.com/projects/16539/challenges/new

**Reproduction Steps:**

1. Open the application and Login as a valid user (jcori)
2. Select a Project > Click Launch New > Fill All > Click Create Challenge
3. Select 'Timeline template' as Standard Code and it will generate the Challenge Schedule (Graph)
4. Click Edit
5. Observe the order of the phases

**Go to the 'Active' tab and select a challenge and click edit from the Challenge Schedule (Graph) and observe the order**

**Actual Result:** 

- Order of the phases are incorrect in Challenge creation process

**Expected Result:** 

- Correct order should be displayed

**Device/OS:** 

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 10 64bit (1909, 18363.815)

**Browser Information:** 

- **Browser(s):** Google Chrome 81.0.4044.138

**Comment by jmgasper** [comment] 2020-05-10 05:58
Contest https://www.topcoder.com/challenges/30124893 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-05-10 05:58
Contest https://www.topcoder.com/challenges/30124893 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by suppermancool** [comment] 2020-05-10 08:05
@jmgasper i can't reproduce this, look like i already fixed this bug in https://github.com/topcoder-platform/challenge-engine-ui/issues/592

**Comment by suppermancool** [comment] 2020-05-10 11:17
@jmgasper right now we can't get the correct order of phases because the timeline don't return the phase order. So for fixing this i have to do patch request right after change timeline without Throttled for getting the correct order.

I think the backend should support order in timeline otherwise we can't use throttled for updating phase in this case

**Comment by suppermancool** [comment] 2020-05-10 11:43
@jmgasper ah wait let me check this again, i think i can make this work with using throttled

**Comment by suppermancool** [comment] 2020-05-10 12:05
@jmgasper done in https://github.com/topcoder-platform/challenge-engine-ui/pull/636.

**Closed** 2020-05-11 01:32 UTC
Labels: Accepted, Functional, May 7 Bug Hunt, tcx_Assigned, tcx_FixAccepted

**Comment by jmgasper** [comment] 2020-05-11 01:38
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30124893<br/><br/>```This is an automated message for ghostar via Topcoder X```
