### ISSUE TITLE
Error displayed while closing a Task

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#816] opened 2020-09-16 18:01 UTC
[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5234047/1.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder.com/ and login as codejam
2. Select a project from the list 'Q2: Customer Experience Prod/Dev Delivery (Connect Projects)'
3. Create a Task and activate it
4. Go to the Active tab and click Edit
5. Click Close and Confirm

### Actual behavior
- An error displayed while closing a Task

### Expected behavior
- Should close the task without any issue

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `codejam`

**Comment by vikasrohit** [comment] 2020-09-17 06:42
@codejamtc could you please some error details directly in the issue description? It is hard to download/unzip to see details for every issue.

**Comment by vikasrohit** [comment] 2020-09-17 06:56
@codejamtc got the details from the archive. I think the issue is same as part 2 in https://github.com/topcoder-platform/challenge-engine-ui/issues/760#issuecomment-692525762. What is happening here is that as soon as you(as non admin user) assigned the task to someone else, that task is out of your authorized challenge/task list and that is why you are observing 403 in console for the challenge.
And there might be other part where it is showing the validation error before hitting Save/Close task buttons is same as of #776

**Comment by vikasrohit** [comment] 2020-09-17 11:28
@codejamtc I have logged separate issue for the first part in my description above:
> What is happening here is that as soon as you(as non admin user) assigned the task to someone else, that task is out of your authorized challenge/task list and that is why you are observing 403 in console for the challenge.

The other part is already logged as issues #776 and #806, so we can close this one now if you don't see any other concern which you want to raise in this issue.

**Closed** 2020-09-17 12:44 UTC
Labels: Functional, P0, Prod Environment
