### ISSUE TITLE
Cannot Proceed w/ Set-Up

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/challenge-engine-ui#761] opened 2020-08-19 15:11 UTC
Was testing Work Manager in PROD (challenges.topcoder.com) and was unable to progress beyond the first set-up screen where I provide Type/Format/Title. I tried refreshing + multiple combinations, and everytime I clicked "Continue Set-Up" nothing happened.

Here are the details:
Browser: Chrome
Environment: Production
Project: https://challenges.topcoder.com/projects/24943/challenges

I can provide a screen recording if helpful.

**Comment by acshields** [comment] 2020-08-19 15:14
@vikasrohit @maxceem - Can you look at this issue to see if there is a quick fix? I have a demo tomorrow with the Expert Services team at Topcoder, but it won't be much of a demo if I can't get past the first screen. lol.

**Comment by maxceem** [comment] 2020-08-19 16:50
@acshields could you, please, add me to the `Topcoder` team to that project you have an issue with, so I could try to have a look? My handle is `maxceem`.

Meanwhile, you might try creating a challenge in this project https://challenges.topcoder.com/projects/24182, I've tried and I could manage to create a new challenge successfully.

> I can provide a screen recording if helpful.

Screen recording would be definitely helpful, especially if you also could open Browser Console, and record the output from there like this:

![image](https://user-images.githubusercontent.com/146016/90665619-f55f1180-e254-11ea-826c-56e7043cadb5.png)

This should open Developer Tools with Browser Console:

![image](https://user-images.githubusercontent.com/146016/90665716-1e7fa200-e255-11ea-8582-866668241343.png)

**Comment by vikasrohit** [comment] 2020-08-24 11:09
@maxceem the root cause for @acshields not able to move forward was because of roles that challenge api honors. Challenge api only allows admins or `copilot` to be able to use the api for creating challenge as of now.

**Comment by ThomasKranitsas** [comment] 2020-09-18 14:56
If the user doesn't have the required role(s) to run a challenge, it's expected to not be able to create one. Please make sure you're testing using a user that has the correct roles.

In case you don't have the required roles, the UI should show a warning.

**Comment by lakshmiathreya** [comment] 2020-09-18 15:23
@acshields could you verify if you are able to Create a Challenge now?

**Comment by vikasrohit** [comment] 2020-09-21 13:46
> If the user doesn't have the required role(s) to run a challenge, it's expected to not be able to create one. Please make sure you're testing using a user that has the correct roles.
> 
> In case you don't have the required roles, the UI should show a warning.

The original problem was that API was not allowing any other user other than admins and `copilot` from creating the challenge API and @acshields neither has admin role nor copilot role. With the support of `Connect Manager` role, @acshields should be able to use the Work Manager on production as well.

**Comment by vikasrohit** [comment] 2020-09-22 03:25
Closing the issue as got confirmation from @acshields on Slack that it is now working for her.

**Closed by vikasrohit** 2020-09-22 03:25 UTC
Labels: Functional, P1, bug
