### ISSUE TITLE
After activating the challenge user can't save details again

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/challenge-engine-ui#804] opened 2020-09-11 20:02 UTC
[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5211316/1.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a challenge with Copilot, Copilot Fee, NDA etc
4. Wait 1 min and activate the challenge
5. Now after few mins click on the same challenge from the Active tab
6. Click Edit
7. Change some values
8. Click Save

### Actual behavior
- After activating the challenge user can't save details again

### Expected behavior
- Should be able to save the changes

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Admin
**- Account used:**  `TonyJ`

**Comment by vikasrohit** [comment] 2020-09-16 12:29
Closing as it is duplicate of #776 and #806.

**Closed by vikasrohit** 2020-09-16 12:29 UTC
Labels: Duplicate, Functional
